# Generated by Django 5.0.3 on 2024-07-17 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_posts_topic"),
    ]

    operations = [
        migrations.AddField(
            model_name="posts",
            name="is_private",
            field=models.BooleanField(default=True),
        ),
    ]
