# Generated by Django 5.0.3 on 2024-07-22 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_topic"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="posts",
            name="topic",
        ),
    ]
