# Generated by Django 5.0.3 on 2024-08-10 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0008_comments_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comments",
            name="user",
        ),
        migrations.RemoveField(
            model_name="posts",
            name="likes",
        ),
    ]
