# Generated by Django 5.0.3 on 2024-08-11 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0010_notifs"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notifs",
            name="users",
        ),
        migrations.AddField(
            model_name="notifs",
            name="target",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notif_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
