# Generated by Django 5.0.3 on 2024-08-11 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0011_remove_notifs_users_notifs_target"),
    ]

    operations = [
        migrations.AddField(
            model_name="notifs",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
    ]
