# Generated by Django 5.0.3 on 2024-08-17 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0012_notifs_is_read"),
    ]

    operations = [
        migrations.AddField(
            model_name="notifs",
            name="url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
