# Generated by Django 5.0.3 on 2024-08-17 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0013_notifs_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notifs",
            name="url",
            field=models.CharField(default="#", max_length=255),
        ),
    ]
