# Generated by Django 5.0.3 on 2024-07-14 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0003_alter_user_followers_alter_user_following"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="sugg1",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Self-Portraits", "Self-Portraits"),
                    ("Art", "Art"),
                    ("Fashion & Style", "Fashion & Style"),
                    ("Products", "Products"),
                    ("Creative Projects", "Creative Projects"),
                    ("Events", "Events"),
                    ("Photography Techniques", "Photography Techniques"),
                    ("Themes & Challenges", "Themes & Challenges"),
                    ("Inspiration & Ideas", "Inspiration & Ideas"),
                    ("Comparisons", "Comparisons"),
                ],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="sugg2",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Self-Portraits", "Self-Portraits"),
                    ("Art", "Art"),
                    ("Fashion & Style", "Fashion & Style"),
                    ("Products", "Products"),
                    ("Creative Projects", "Creative Projects"),
                    ("Events", "Events"),
                    ("Photography Techniques", "Photography Techniques"),
                    ("Themes & Challenges", "Themes & Challenges"),
                    ("Inspiration & Ideas", "Inspiration & Ideas"),
                    ("Comparisons", "Comparisons"),
                ],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="sugg3",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Self-Portraits", "Self-Portraits"),
                    ("Art", "Art"),
                    ("Fashion & Style", "Fashion & Style"),
                    ("Products", "Products"),
                    ("Creative Projects", "Creative Projects"),
                    ("Events", "Events"),
                    ("Photography Techniques", "Photography Techniques"),
                    ("Themes & Challenges", "Themes & Challenges"),
                    ("Inspiration & Ideas", "Inspiration & Ideas"),
                    ("Comparisons", "Comparisons"),
                ],
                null=True,
            ),
        ),
    ]
