# Generated by Django 5.0.3 on 2024-08-05 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0004_user_sugg1_user_sugg2_user_sugg3"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="full_name",
        ),
        migrations.AddField(
            model_name="user",
            name="details_provided",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="location",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="sugg4",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Self-Portraits", "Self-Portraits"),
                    ("Art", "Art"),
                    ("Fashion & Style", "Fashion & Style"),
                    ("Products", "Products"),
                    ("Creative Projects", "Creative Projects"),
                    ("Events", "Events"),
                    ("Photography Techniques", "Photography Techniques"),
                    ("Themes & Challenges", "Themes & Challenges"),
                    ("Inspiration & Ideas", "Inspiration & Ideas"),
                    ("Comparisons", "Comparisons"),
                ],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="yang",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
    ]
