# Generated by Django 5.0.3 on 2024-08-09 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0005_remove_user_full_name_user_details_provided_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="posts",
        ),
    ]
